### ISSUE TITLE
Install AAP2.4 using terraform

### ISSUE THREAD

**Issue by Srikanth1992** [ansible/terraform-provider-aap#14]
Hello Team

Currently, our organization runs Ansible Automation Platform (AAP) version 2.4 on RHEL 8. We have a setup with 4 nodes, including 3 HA nodes and 1 database node managed by a controller. This setup was manually done on AWS. Now, we’re considering setting up new AAP environments using Terraform and also want to handle data restoration. I’m searching for existing Terraform modules to facilitate this transition. Our aim is to fully automate the setup process.

Can anyone please share any references materials I can use to move forward.

**Comment by gravesm** [comment]
@Srikanth1992 This repo is for the currently unreleased Terraform provider for automating an existing AAP instance. I'm fairly certain that Terraform is not a supported installation method for AAP, and as such, there would not be any reference material available. Your best bet will be to try filing a support request as they will be more knowledgeable about supported installation methods.
