### ISSUE TITLE
Broken Link In README.md

### ISSUE THREAD

**Issue by Jonx1000** [ansible/terraform-provider-aap#15]
The `README.md` file contains a broken link, https://registry.terraform.io/providers/ansible/aap/latest, which is supposed to be pointing to the `aap` provider in the terraform registry. The profile only appears to contain an `ansible` provider and currently does not have an `aap` provider.

![Screenshot 2024-03-20 at 7 50 49 AM](https://github.com/ansible/terraform-provider-aap/assets/38022845/9301e31a-7e0d-485c-9899-ec32799c8b93)

![image](https://github.com/ansible/terraform-provider-aap/assets/38022845/8bb8de2e-950a-4b0b-b20a-6dacf7dc0f4d)

**Comment by gravesm** [comment]
@Jonx1000 Thanks for your interest in the AAP provider. This is still under development and has not yet been released. The link will be active once it has been published.
